### PR TITLE
Amf failure fixing

### LINKED ISSUE #68: Encoder fails to start if AMF is enabled but not available

### PR DESCRIPTION
**Pull request by tataRinaz**
Fixed problem with crash if an codec found but unavailable
Closes #68

### CODE REVIEW

File: src/encoder/ffmpeg.cpp [hunk 1]
```diff
@@ -83,8 +106,15 @@ static AVCodec* select_codec(Logger& logger, const ConfigPtr& config){
...
-      logger.info("Using {} encoder", name);
-      return codec;
+
+      auto* context = make_context(config, codec, frame_size, fps);
+      if (avcodec_open2(context, codec, &opts->get_ptr()) >= 0) {
+        logger.info("Using {} encoder", name);
+        return codec;
+      }
+      else {
+        avcodec_close(context);
```
Comment (0xd34d10cc) [inline src/encoder/ffmpeg.cpp]: `avcodec_free_context` should also be called here

File: src/encoder/ffmpeg.cpp [hunk 2]
```diff
@@ -128,7 +139,11 @@ Codec::Codec(Size frame_size, std::size_t fps, Logger logger, const ConfigPtr& c
     }
   }
 
-  if (avcodec_open2(m_context, m_encoder, &opts.get_ptr()) < 0) {
+  m_encoder = select_codec(m_logger, config, &opts, frame_size, fps);
+  assert(m_encoder);
+
+  m_context = make_context(config, m_encoder, frame_size, fps);
```
Comment (0xd34d10cc) [inline src/encoder/ffmpeg.cpp]: But context was already allocated and initialized in `select_codec` function.

File: src/encoder/ffmpeg.cpp [hunk 3]
```diff
@@ -128,7 +139,11 @@ Codec::Codec(Size frame_size, std::size_t fps, Logger logger, const ConfigPtr& c
...
+  if (avcodec_open2(m_context, m_encoder, &opts.get_ptr())<0) {
```
Comment (0xd34d10cc) [inline src/encoder/ffmpeg.cpp]: ... and `open`'ed

File: src/encoder/ffmpeg.hpp [hunk 4]
```diff
@@ -11,7 +11,9 @@
 
 struct AVCodec;
 struct AVCodecContext;
-
+namespace {
+  class  Options;
```
Comment (0xd34d10cc) [inline src/encoder/ffmpeg.hpp]: Why? `Options` class is local to ffmpeg.cpp and not used anywhere else.

File: src/encoder/ffmpeg.cpp [hunk 5]
```diff
@@ -59,7 +59,30 @@ class Options {
...
 namespace shar::codecs::ffmpeg {
 
-static AVCodec* select_codec(Logger& logger, const ConfigPtr& config){
+static AVCodecContext* make_context(const ConfigPtr& config, AVCodec* codec, Size frame_size, std::size_t fps) {
+
+  AVCodecContext* context = avcodec_alloc_context3(codec);
+  assert(context);
+
+  std::fill_n(reinterpret_cast<char*>(context), sizeof(AVCodecContext), 0);
+  const std::size_t kbits = config->get<std::size_t>("bitrate", 5000);
```
Comment (0xd34d10cc) [inline src/encoder/ffmpeg.cpp]: Looks like `config` is used only to get `bitrate`, so `config` parameter of this function could be replaced by `bitrate`.

File: src/encoder/ffmpeg.cpp [hunk 6]
```diff
@@ -59,7 +59,30 @@ class Options {
...
+  context->max_pixels = context->width * context->height;
+
+  std::size_t divisor = std::gcd(frame_size.width(), frame_size.height());
+  context->sample_aspect_ratio.num = static_cast<int>(frame_size.width() / divisor);
+  context->sample_aspect_ratio.den = static_cast<int>(frame_size.height() / divisor);
+
+  return context;
+}
+
+static AVCodec* select_codec(Logger& logger,const ConfigPtr& config, Options* opts, Size frame_size, std::size_t fps){
```
Comment (0xd34d10cc) [inline src/encoder/ffmpeg.cpp]: Pass `Options` by reference.

File: src/encoder/ffmpeg.cpp [hunk 7]
```diff
@@ -13,195 +13,213 @@ extern "C" {
...
+    const std::size_t kbits = config->get<std::size_t>("bitrate", 5000);
+    if (!codec_name.empty()) {
+      if (auto* codec = avcodec_find_encoder_by_name(codec_name.c_str())) {
+        m_logger.info("Using {} encoder from config", codec_name);
+        m_encoder = codec;
+        m_context = make_context(kbits, codec, frame_size, fps);
+        if (avcodec_open2(m_context, codec, &opts.get_ptr()) >= 0) {
+          m_logger.info("Using {} encoder", codec_name);
+          return;
+        }
```
Comment (0xd34d10cc) [inline src/encoder/ffmpeg.cpp]: `m_context` is not released in `else` case.  Also, you have removed the warning.

File: src/encoder/ffmpeg.hpp (hunk 4 above)
Comment (0xd34d10cc) [reply src/encoder/ffmpeg.hpp]: I think we should have RAII wrappers for AVContext and AVCodec.

File: src/encoder/ffmpeg.cpp (hunk 7 above)
Comment (0xd34d10cc) [reply src/encoder/ffmpeg.cpp]: I think we should have RAII wrappers for AVContext and AVCodec to avoid such errors.

File: src/encoder/ffmpeg/codec.cpp [hunk 8]
```diff
@@ -0,0 +1,96 @@
...
+
+  av_frame_free(&frame);
+  return packets;
+}
+
+int Codec::get_pts() {
+  return static_cast<int>(CLOCK_RATE / static_cast<unsigned int>(m_context.get()->time_base.den) * m_frame_counter++);
+}
+
+Codec::~Codec() {
```
Comment (0xd34d10cc) [inline src/encoder/ffmpeg/codec.cpp]: `= default`

File: src/encoder/ffmpeg/codec.cpp [hunk 9]
```diff
@@ -0,0 +1,96 @@
...
+  for (const auto& iter : *options) {
+    const char* key = iter.first.c_str();
+    const std::string value = iter.second.get_value<std::string>();
+
+    if (!opts.set(key, value.c_str())) {
+      m_logger.error("Failed to set {} encoder option to {}. Ignoring", key, value);
+    }
+  }
+
+  m_encoder = std::move(AVCodecPtr(m_logger, config, m_context, opts, frame_size, fps));
```
Comment (0xd34d10cc) [inline src/encoder/ffmpeg/codec.cpp]: Redundant `std::move`

File: src/encoder/ffmpeg/avcodec.hpp [hunk 10]
```diff
@@ -0,0 +1,38 @@
...
+class ContextPtr;
+
+namespace shar::codecs::ffmpeg {
+
+class AVCodecPtr {
+
+public:
+  AVCodecPtr() = default;
+  AVCodecPtr(Logger& logger, const ConfigPtr& config, ContextPtr& context, Options& options, Size frame_size, std::size_t fps);
+  ~AVCodecPtr() = default;
```
Comment (0xd34d10cc) [inline src/encoder/ffmpeg/avcodec.hpp]: There is no point in writing RAII wrapper if destructor is default. This entire class could be replaced by single function.

File: src/encoder/ffmpeg/avcontext.hpp [hunk 11]
```diff
@@ -0,0 +1,35 @@
+#pragma once
+
+#include "disable_warnings_push.hpp"
+extern "C" {
+#include <libavcodec/avcodec.h>
```
Comment (0xd34d10cc) [inline src/encoder/ffmpeg/avcontext.hpp]: Either remove this include and forward declare `AVCodec` or remove forward declaration of `AVCodecContext`
