### PR TITLE
Error codes instead of exceptions in RTSP parsers

### LINKED ISSUE #220: Use error codes in rtsp parser instead of exceptions

### PR DESCRIPTION
**Pull request by tataRinaz**
Closes #220

### CODE REVIEW

File: src/net/rtsp/parser.cpp [hunk 1]
```diff
@@ -6,36 +6,32 @@
 
 namespace shar::net::rtsp {
 
-std::optional<std::uint8_t> parse_version(const char* begin, std::size_t size) {
+#define FAIL(code) return make_error_code(code)
```
Comment (0xd34d10cc) [inline src/net/rtsp/parser.cpp]: Use macro from `error_or.hpp`

File: src/net/rtsp/parser.cpp [hunk 2]
```diff
@@ -6,36 +6,32 @@
...
+
+ErrorOr<std::uint8_t> parse_version(const char* begin, std::size_t size) {
   if (size > 8) {
-    throw std::runtime_error("Incorrect protocol version");
+    FAIL(Error::invalidProtocol);
```
Comment (0xd34d10cc) [inline src/net/rtsp/parser.cpp]: Use `PascalCase` instead of `camelCase` for names of enum variants

File: src/net/rtsp/parser.cpp [hunk 3]
```diff
@@ -44,60 +40,67 @@ Header parse_header(const char* begin, std::size_t size) {
...
-      return std::nullopt;
+    if (*header_end == end) {
+      FAIL(Error::notEnoughData);
     }
-    std::size_t header_size = header_end.value() - header_begin;
+    std::size_t header_size = *header_end - header_begin;
 
-    auto[key, value] = parse_header(header_begin, header_size);
+    auto header = parse_header(header_begin, header_size);
+    if (header.err()) {
```
Comment (0xd34d10cc) [inline src/net/rtsp/parser.cpp]: Use `TRY` macro from `error_or.hpp`

File: src/net/CMakeLists.txt [hunk 4]
```diff
@@ -66,6 +66,7 @@ add_library(net
     rtsp/serializer.cpp
     rtsp/server.hpp
     rtsp/server.cpp
+    rtsp/request_error.hpp
```
Comment (0xd34d10cc) [inline src/net/CMakeLists.txt]: Naming: request_error is also used for response parsing

File: src/net/rtsp/request.cpp [hunk 5]
```diff
@@ -69,52 +69,54 @@ std::optional<std::size_t> Request::parse(const char * buffer, const std::size_t
...
-    return std::nullopt;
+  if (*version_end == end) {
+    FAIL(Error::notEnoughData);
   }
-  m_version = version;
+  m_version = *version;
   //Check for requests ending without line ending
-  if (version_end.value() + 2 == end) {
-    return std::nullopt;
+  if (*version_end + 2 == end) {
```
Comment (0xd34d10cc) [inline src/net/rtsp/request.cpp]: And what if `version_end+1 == end`?

File: src/net/rtsp/request.cpp [hunk 6]
```diff
@@ -136,9 +138,9 @@ static char* type_to_string(Request::Type type) {
 
 }
 
-bool Request::serialize(char* destination, std::size_t size) {
+ErrorOr<bool> Request::serialize(char* destination, std::size_t size) {
   if (!m_type.has_value() || !m_address.has_value() || !m_version.has_value()) {
-    throw std::runtime_error("One of fields is not initialized");
+    FAIL(Error::unitializedField);
```
Comment (0xd34d10cc) [inline src/net/rtsp/request.cpp]: This is error of programmer, not user. `assert` should be used for these kinds of errors.

File: src/net/rtsp/request.hpp [hunk 7]
```diff
@@ -27,9 +27,9 @@ struct Request {
     RECORD
   };
 
-  std::optional<std::size_t> parse(const char* buffer, std::size_t size);
+  ErrorOr<std::size_t> parse(const char* buffer, std::size_t size);
 
-  bool serialize(char* destination, std::size_t);
+  ErrorOr<bool> serialize(char* destination, std::size_t);
```
Comment (0xd34d10cc) [inline src/net/rtsp/request.hpp]: Please add a comment what `bool `means here.

File: src/net/rtsp/server.cpp [hunk 8]
```diff
@@ -99,34 +98,36 @@ void Server::receive_request(ClientPos client_pos) {
       disconnect_client(client_pos);
       return;
     }
+    auto& client = client_pos->second;
+    Request request({ client.m_headers.data(), client.m_headers.size() });
+    client.m_received_bytes += size;
+    auto parsing_result = request.parse(reinterpret_cast<const char*>(client.m_buffer.data()), client.m_received_bytes);
 
-    try {
+    if (parsing_result.err().value() == static_cast<int>(Error::notEnoughData)) {
```
Comment (0xd34d10cc) [inline src/net/rtsp/server.cpp]: `.value()` will throw exception if there were no error

File: src/net/rtsp/request_error.hpp [hunk 9]
```diff
@@ -4,16 +4,16 @@
...
+  Success = 0,
+  NotEnoughData,
+  InvalidAddress,
+  InvalidProtocol,
+  InvalidHeader,
+  InvalidStatusCode,
+  InvalidType,
+  ExcessHeaders,
+  MissingCRLF,
+  UnitializedField
```
Comment (0xd34d10cc) [inline src/net/rtsp/request_error.hpp]: Unused variant

File: src/net/rtsp/response.cpp [hunk 10]
```diff
@@ -19,61 +19,51 @@ ErrorOr<std::size_t> Response::parse(const char * buffer, std::size_t size)
...
 
   return response_line_size + *headers_len;
 }
 
 ErrorOr<std::size_t> Response::serialize(char* destination, std::size_t size) {
-  if (!m_version.has_value() || !m_reason.has_value() ||
-       m_status_code == std::numeric_limits<std::uint16_t>::max()) {
-    FAIL(Error::unitializedField);
-  }
+  assert(m_version.has_value() || m_reason.has_value() ||
```
Comment (0xd34d10cc) [inline src/net/rtsp/response.cpp]: It should be `&&`, not `||`
